sudo: required
services:
        - docker

before_install:
        - docker build -t pradiptab/docker-react -f Dockerfile.dev .

script:
        - docker run pradiptab/docker-react npm run test -- --coverage
